// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using invoice_v1.src.Infrastructure.Data;

#nullable disable

namespace invoice_v1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204092836_RepositoryAdded")]
    partial class RepositoryAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.FileChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GoogleDriveModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("IX_FileChangeLogs_ChangeType");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_FileChangeLogs_FileId");

                    b.HasIndex("Processed", "DetectedAt")
                        .HasDatabaseName("IX_FileChangeLogs_Processed_DetectedAt");

                    b.ToTable("FileChangeLogs");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvalidInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_InvalidInvoices_FileId");

                    b.ToTable("InvalidInvoices", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillToName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShipMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipToCity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipToCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShipToState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BillToName")
                        .HasDatabaseName("IX_Invoices_BillToName");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Invoices_CreatedAt");

                    b.HasIndex("DriveFileId")
                        .IsUnique()
                        .HasDatabaseName("IX_Invoices_DriveFileId_Unique");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("IX_Invoices_InvoiceDate");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("IX_Invoices_InvoiceNumber");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Invoices_OrderId");

                    b.HasIndex("VendorName")
                        .HasDatabaseName("IX_Invoices_VendorName");

                    b.HasIndex("InvoiceDate", "TotalAmount")
                        .HasDatabaseName("IX_Invoices_Date_Amount");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_InvoiceLines_Category");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductGuid")
                        .HasDatabaseName("IX_InvoiceLines_ProductGuid");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_InvoiceLines_ProductId");

                    b.HasIndex("ProductGuid", "InvoiceId")
                        .HasDatabaseName("IX_InvoiceLines_Product_Invoice");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.JobQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_JobQueues_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_JobQueues_Status");

                    b.HasIndex("LockedBy", "LockedAt")
                        .HasDatabaseName("IX_JobQueues_LockedBy_LockedAt");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("IX_JobQueues_Status_NextRetryAt");

                    b.ToTable("JobQueues");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DefaultUnitRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSoldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecondaryCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalQuantitySold")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    b.HasIndex("LastSoldDate")
                        .HasDatabaseName("IX_Products_LastSoldDate");

                    b.HasIndex("PrimaryCategory")
                        .HasDatabaseName("IX_Products_PrimaryCategory");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_ProductId_Unique");

                    b.HasIndex("TotalQuantitySold")
                        .HasDatabaseName("IX_Products_TotalQuantitySold");

                    b.HasIndex("TotalRevenue")
                        .HasDatabaseName("IX_Products_TotalRevenue");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("invoice_v1.src.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invoice_v1.src.Domain.Entities.Product", "Product")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("ProductGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Product", b =>
                {
                    b.Navigation("InvoiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
