using invoice_v1.src.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace invoice_v1.src.Infrastructure.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        // DbSets
        public DbSet<FileChangeLog> FileChangeLogs { get; set; } = null!;
        public DbSet<JobQueue> JobQueues { get; set; } = null!;
        public DbSet<Product> Products { get; set; } = null!;
        public DbSet<Invoice> Invoices { get; set; } = null!;
        public DbSet<InvoiceLine> InvoiceLines { get; set; } = null!;
        public DbSet<InvalidInvoice> InvalidInvoices { get; set; } = null!;
        public DbSet<Vendor> Vendors { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            ConfigureFileChangeLog(modelBuilder);
            ConfigureJobQueue(modelBuilder);
            ConfigureVendor(modelBuilder);
            ConfigureProduct(modelBuilder);
            ConfigureInvoice(modelBuilder);
            ConfigureInvoiceLine(modelBuilder);
            ConfigureInvalidInvoice(modelBuilder);
        }

        private static void ConfigureFileChangeLog(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FileChangeLog>(entity =>
            {
                entity.HasKey(e => e.Id);

                // GUID is not auto-generated by database
                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                entity.Property(e => e.ChangeType)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.DetectedAt)
                    .IsRequired();

                // Index for polling unprocessed logs
                entity.HasIndex(e => new { e.Processed, e.DetectedAt })
                    .HasDatabaseName("IX_FileChangeLogs_Processed_DetectedAt");

                // Index for FileId lookups
                entity.HasIndex(e => e.FileId)
                    .HasDatabaseName("IX_FileChangeLogs_FileId");

                entity.HasIndex(e => e.ChangeType)
                    .HasDatabaseName("IX_FileChangeLogs_ChangeType");

                // NEW: Index on ModifiedBy for vendor filtering
                entity.HasIndex(e => e.ModifiedBy)
                    .HasDatabaseName("IX_FileChangeLogs_ModifiedBy");
            });
        }

        private static void ConfigureJobQueue(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<JobQueue>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                entity.Property(e => e.JobType)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Status)
                    .IsRequired()
                    .HasMaxLength(50);

                // CHANGE 1: PostgreSQL JSONB instead of nvarchar(max)
                entity.Property(e => e.PayloadJson)
                    .IsRequired()
                    .HasColumnType("jsonb");

                entity.HasIndex(e => new { e.Status, e.NextRetryAt })
                    .HasDatabaseName("IX_JobQueues_Status_NextRetryAt");

                entity.HasIndex(e => e.Status)
                    .HasDatabaseName("IX_JobQueues_Status");

                entity.HasIndex(e => new { e.LockedBy, e.LockedAt })
                    .HasDatabaseName("IX_JobQueues_LockedBy_LockedAt");

                entity.HasIndex(e => e.CreatedAt)
                    .HasDatabaseName("IX_JobQueues_CreatedAt");

                // CHANGE 1 (continued): Add GIN index for JSONB queries
                entity.HasIndex(e => e.PayloadJson)
                    .HasMethod("gin")
                    .HasDatabaseName("IX_JobQueues_PayloadJson_Gin");
            });
        }

        private static void ConfigureVendor(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Vendor>(entity =>
            {
                entity.HasKey(v => v.Email);

                entity.Property(v => v.Email)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(v => v.DisplayName)
                    .HasMaxLength(200);

                entity.Property(v => v.FirstSeenAt)
                    .IsRequired();

                entity.Property(v => v.LastActivityAt)
                    .IsRequired();

                // Index on Email (primary key is already indexed)
                entity.HasIndex(v => v.Email)
                    .IsUnique()
                    .HasDatabaseName("IX_Vendors_Email");

                // Index on LastActivityAt for sorting
                entity.HasIndex(v => v.LastActivityAt)
                    .HasDatabaseName("IX_Vendors_LastActivityAt");

                // One vendor has many invoices
                entity.HasMany(v => v.Invoices)
                    .WithOne(i => i.Vendor)
                    .HasForeignKey(i => i.VendorEmail)
                    .OnDelete(DeleteBehavior.Restrict);

                // One vendor has many products
                entity.HasMany(v => v.Products)
                    .WithOne(p => p.Vendor)
                    .HasForeignKey(p => p.VendorEmail)
                    .OnDelete(DeleteBehavior.Restrict);
            });
        }

        private static void ConfigureProduct(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                // NEW: VendorEmail is required
                entity.Property(e => e.VendorEmail)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.ProductId)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ProductName)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.HasIndex(e => new { e.VendorEmail, e.ProductId })
                    .IsUnique()
                    .HasDatabaseName("IX_Products_VendorEmail_ProductId_Unique");

                // NEW: Index on VendorEmail for RBAC filtering
                entity.HasIndex(e => e.VendorEmail)
                    .HasDatabaseName("IX_Products_VendorEmail");

                // Keep original ProductId index for queries (not unique anymore)
                entity.HasIndex(e => e.ProductId)
                    .HasDatabaseName("IX_Products_ProductId");

                entity.HasIndex(e => e.PrimaryCategory)
                    .HasDatabaseName("IX_Products_PrimaryCategory");

                entity.HasIndex(e => e.Category)
                    .HasDatabaseName("IX_Products_Category");

                entity.HasIndex(e => e.TotalQuantitySold)
                    .HasDatabaseName("IX_Products_TotalQuantitySold");

                entity.HasIndex(e => e.TotalRevenue)
                    .HasDatabaseName("IX_Products_TotalRevenue");

                entity.HasIndex(e => e.LastSoldDate)
                    .HasDatabaseName("IX_Products_LastSoldDate");
            });
        }

        private static void ConfigureInvoice(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                // NEW: VendorEmail is required
                entity.Property(e => e.VendorEmail)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.DriveFileId)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasIndex(e => e.DriveFileId)
                    .IsUnique()
                    .HasDatabaseName("IX_Invoices_DriveFileId_Unique");

                // NEW: Composite unique constraint (VendorEmail, InvoiceNumber)
                // Allows different vendors to have same invoice number
                entity.HasIndex(e => new { e.VendorEmail, e.InvoiceNumber })
                    .IsUnique()
                    .HasDatabaseName("IX_Invoices_VendorEmail_InvoiceNumber_Unique");

                // NEW: Index on VendorEmail for RBAC filtering
                entity.HasIndex(e => e.VendorEmail)
                    .HasDatabaseName("IX_Invoices_VendorEmail");

                entity.HasIndex(e => e.InvoiceNumber)
                    .HasDatabaseName("IX_Invoices_InvoiceNumber");

                entity.HasIndex(e => e.OrderId)
                    .HasDatabaseName("IX_Invoices_OrderId");

                entity.HasIndex(e => e.InvoiceDate)
                    .HasDatabaseName("IX_Invoices_InvoiceDate");

                entity.HasIndex(e => e.VendorName)
                    .HasDatabaseName("IX_Invoices_VendorName");

                entity.HasIndex(e => e.BillToName)
                    .HasDatabaseName("IX_Invoices_BillToName");

                entity.HasIndex(e => new { e.InvoiceDate, e.TotalAmount })
                    .HasDatabaseName("IX_Invoices_Date_Amount");

                entity.HasIndex(e => e.CreatedAt)
                    .HasDatabaseName("IX_Invoices_CreatedAt");

                // Add JSONB configuration for ExtractedDataJson
                entity.Property(e => e.ExtractedDataJson)
                    .HasColumnType("jsonb");

                // Add GIN index for JSONB queries
                entity.HasIndex(e => e.ExtractedDataJson)
                    .HasMethod("gin")
                    .HasDatabaseName("IX_Invoices_ExtractedDataJson_Gin");
            });
        }

        private static void ConfigureInvoiceLine(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<InvoiceLine>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                entity.Property(e => e.ProductId)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ProductName)
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.Quantity)
                    .IsRequired()
                    .HasColumnType("decimal(18,4)");

                entity.Property(e => e.UnitRate)
                    .IsRequired()
                    .HasColumnType("decimal(18,2)");

                entity.Property(e => e.Amount)
                    .IsRequired()
                    .HasColumnType("decimal(18,2)");

                entity.HasOne(e => e.Invoice)
                    .WithMany(i => i.LineItems)
                    .HasForeignKey(e => e.InvoiceId)
                    .OnDelete(DeleteBehavior.Cascade);

                entity.HasOne(e => e.Product)
                    .WithMany(p => p.InvoiceLines)
                    .HasForeignKey(e => e.ProductGuid)
                    .OnDelete(DeleteBehavior.Restrict);

                entity.HasIndex(e => e.ProductGuid)
                    .HasDatabaseName("IX_InvoiceLines_ProductGuid");

                entity.HasIndex(e => e.ProductId)
                    .HasDatabaseName("IX_InvoiceLines_ProductId");

                entity.HasIndex(e => e.Category)
                    .HasDatabaseName("IX_InvoiceLines_Category");

                entity.HasIndex(e => new { e.ProductGuid, e.InvoiceId })
                    .HasDatabaseName("IX_InvoiceLines_Product_Invoice");
            });
        }

        private static void ConfigureInvalidInvoice(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<InvalidInvoice>(entity =>
            {
                entity.ToTable("InvalidInvoices");

                entity.HasKey(e => e.Id);

                entity.Property(e => e.Id)
                    .ValueGeneratedNever();

                // VendorEmail (nullable for backward compatibility)
                entity.Property(e => e.VendorEmail)
                    .HasMaxLength(200);

                // Index on VendorEmail for RBAC filtering
                entity.HasIndex(e => e.VendorEmail)
                    .HasDatabaseName("IX_InvalidInvoices_VendorEmail");

                entity.HasIndex(e => e.FileId)
                    .HasDatabaseName("IX_InvalidInvoices_FileId");

                entity.Property(e => e.FileName)
                    .HasMaxLength(500);

                entity.Property(e => e.FileId)
                    .HasMaxLength(100);

                // PostgreSQL text instead of nvarchar(max)
                entity.Property(e => e.Reason)
                    .IsRequired()
                    .HasColumnType("text");

                entity.Property(e => e.CreatedAt)
                    .IsRequired();
            });
        }
    }
}
